version: '3.5'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - proxynet

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 3031:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - proxynet
    depends_on:
      - mysql
    links:
      - mysql
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - proxynet
networks:
  proxynet:
    name: kg-network
